# Generated by Django 5.2.4 on 2025-08-05 17:02

import apps.documents.validations
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField(verbose_name='Company ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_categories', to='participants.participant', verbose_name='Participant')),
            ],
            options={
                'verbose_name': 'Document Category',
                'verbose_name_plural': 'Document Categories',
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('private_visible', models.BooleanField(default=False, verbose_name='Private Visible')),
                ('public_visible', models.BooleanField(default=False, verbose_name='Public Visible')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_types', to='documents.documentcategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Document Type',
                'verbose_name_plural': 'Document Types',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField(verbose_name='Company ID')),
                ('file', models.FileField(upload_to='documents/', validators=[apps.documents.validations.validate_pdf_file], verbose_name='File')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='participants.participant', verbose_name='Participant')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='documents.documenttype', verbose_name='Document Type')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
        migrations.CreateModel(
            name='UploadedTextFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_texts', to='documents.document', verbose_name='Document')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_texts', to='documents.documenttype', verbose_name='Document Type')),
            ],
            options={
                'verbose_name': 'Uploaded Text File',
                'verbose_name_plural': 'Uploaded Text Files',
            },
        ),
    ]
